export const CATEGORIES = [
  'Médicaments',
  'Dermo-Cosmétique',
  'Bébé & Maman',
  'Compléments Alimentaires',
  'Hygiène & Soins',
  'Phytothérapie & Aromathérapie',
  'Matériel Médical & Orthopédie',
  'Préparations Officinales',
  'Vétérinaire',
  'Produits Chimiques',
  'Autre',
] as const;

export const DOSAGE_FORMS = [
  'Comprimés',
  'Gélules',
  'Sirops',
  'Solutions buvables',
  'Sachets',
  'Granules',
  'Crèmes',
  'Pommades',
  'Gels',
  'Lotions',
  'Baumes',
  'Sticks',
  'Ampoules injectables',
  'Flacons',
  'Stylos pré-remplis',
  'Seringues pré-remplies',
  'Sprays Nasaux',
  'Collyres',
  'Gouttes auriculaires',
  'Aérosols',
  'Suppositoires',
  'Ovules',
  'Crèmes vaginales',
  'Tisanes',
  "Sprays d'eau thermale",
  'Patchs',
] as const;

export const ZONES = [
  'Zone Médicaments',
  'Zone Dermo-Cosmétique',
  'Zone Hygiène Capillaire',
  'Zone Hygiène Bucco-dentaire',
  'Zone Bébé & Maman',
  'Zone Compléments Alimentaires',
  'Zone Phytothérapie & Aromathérapie',
  'Zone Orthopédie',
  'Zone Matériel Médical',
  'Zone Premiers Secours',
  'Zone Solaire',
  'Zone Hygiène Intime',
  'Zone Optique',
  'Zone Vétérinaire',
  'Zone Produits Chimiques',
  'Zone Préparations Officinales',
  'Zone OTC',
  'Zone Tiroirs',
  'Zone Frigo',
  'Zone Coffre',
  'Zone Réception',
  'Zone Déstockage',
  'Zone Périmés',
] as const;

export const ACTIVE_OPTIONS = [
  { value: true, label: 'Oui' },
  { value: false, label: 'Non' },
] as const;